version: "3.7"

services:
  next-app:
    container_name: next-app
    restart: always
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    ports:
      - "8072:3000"
    networks:
      - next-net

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - next-app
    networks:
      - next-net

networks:
  next-net:
    driver: bridge
